## Default Logstash configuration from logstash-docker.
## from https://github.com/elastic/logstash-docker/blob/master/build/logstash/config/logstash-oss.yml
##
http.host: "0.0.0.0"

#xpack.monitoring.elasticsearch.username: logstash_system
#xpack.monitoring.elasticsearch.password: LmzRkRNVIcwB7ZqHQq4I
#xpack.monitoring.enabled: true
#xpack.monitoring.elasticsearch.url: "http://10.0.0.174:9200/"


pipeline.id: main
pipeline.workers: 2
#path.plugins: /usr/share/logstash/plugins/logstash-input-facebook/lib/logstash/inputs/facebook.rb


config.reload.interval: 60s
config.test_and_exit: false
config.reload.automatic: true


